[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gardener/gardener"
  version = "0.14.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "9dfdf9be683f61f82cda12362c44c784e0778b56" # kubernetes-1.12.1
